// src/features/shell/background/lib-vue/DNASparkBackground.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useColorMode } from '../vue/useColorMode';
import BackgroundCanvas from '../vue/BackgroundCanvas.vue';
import type { BackgroundFrame } from '../vue/useBackgroundCanvas';
import { ObjectPool } from '../lib/objectPool';

const props = withDefaults(
  defineProps<{
    sparkColor?: string;
    strandColor?: string;
    className?: string;
    particleColor?: string;
    connectionColor?: string;
    rippleColor?: string;
    color?: string;
    constfill?: string;
    text?: string;
  }>(),
  {}
);

interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
  size: number;
  opacity: number;
  angle: number;
  speed: number;
}

interface TrailPoint {
  x: number;
  y: number;
  opacity: number;
}

interface BasePair {
  base1: string;
  base2: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  z1: number;
  z2: number;
  glowIntensity: number;
  isVisible: boolean;
  startX1: number;
  startY1: number;
  startX2: number;
  startY2: number;
  animationProgress: number;
  velocityX: number;
  velocityY: number;
  trail: TrailPoint[];
}

interface LocalRipple {
  x: number;
  y: number;
  radius: number;
  opacity: number;
}

const mode = useColorMode();
const sparkColor = props.sparkColor || (mode.value === 'dark' ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.7)');
const strandColor = props.strandColor || (mode.value === 'dark' ? 'rgba(64,224,208,0.6)' : 'rgba(0,0,0,0.2)');
const particleColor = props.particleColor || (mode.value === 'dark' ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.7)');
const connectionColor = props.connectionColor || (mode.value === 'dark' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.08)');
const rippleColor = props.rippleColor || (mode.value === 'dark' ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.08)');

const ripplePoolRef = ref(
  new ObjectPool<LocalRipple>(
    () => ({ x: 0, y: 0, radius: 0, opacity: 0 }),
    (r) => {
      r.x = 0;
      r.y = 0;
      r.radius = 0;
      r.opacity = 0;
    },
    50
  )
);

const particlesRef = ref<Particle[]>([]);
const basePairsRef = ref<BasePair[]>([]);
const ripplesRef = ref<LocalRipple[]>([]);
const initialAnimationCompleteRef = ref(false);
const shatterProgressRef = ref(0);
const isShatteringRef = ref(false);
const lastSizeRef = ref<{ width: number; height: number }>({ width: 0, height: 0 });

const baseColors: Record<string, string> = {
  A: '#1A88FF',
  T: '#E1AD37',
  G: '#AA88FF',
  C: '#AA88FF',
};

const getComplementaryBase = (base: string) => {
  const pairs: Record<string, string> = { A: 'T', T: 'A', G: 'C', C: 'G' };
  return pairs[base] || 'A';
};

const generateOrderedSequence = (length: number) => {
  const pattern = ['A', 'T', 'G', 'C'];
  return Array.from({ length }, (_, i) => pattern[i % pattern.length]);
};

function initParticles(width: number, height: number) {
  const particles: Particle[] = [];
  const numParticles = Math.floor((width * height) / 8000);
  for (let i = 0; i < numParticles; i++) {
    particles.push({
      x: Math.random() * width,
      y: Math.random() * height,
      vx: (Math.random() - 0.5) * 0.5,
      vy: (Math.random() - 0.5) * 0.5,
      size: Math.random() * 2 + 1,
      opacity: Math.random() * 0.5 + 0.3,
      angle: Math.random() * Math.PI * 2,
      speed: Math.random() * 0.02 + 0.01,
    });
  }
  return particles;
}

function initBasePairs(width: number, height: number) {
  const basePairs: BasePair[] = [];
  const sequence = generateOrderedSequence(Math.floor(height / 25));
  for (let i = 0; i < sequence.length; i++) {
    const base2 = sequence[i];
    const base1 = getComplementaryBase(base2);
    const startX1 = Math.random() * width;
    const startY1 = Math.random() * height;
    const startX2 = Math.random() * width;
    const startY2 = Math.random() * height;
    basePairs.push({
      base1,
      base2,
      x1: startX1,
      y1: startY1,
      x2: startX2,
      y2: startY2,
      z1: 0,
      z2: 0,
      glowIntensity: 0,
      isVisible: true,
      startX1,
      startY1,
      startX2,
      startY2,
      animationProgress: 0,
      velocityX: 0,
      velocityY: 0,
      trail: [],
    });
  }
  return basePairs;
}

function init(_canvas: HTMLCanvasElement, frame: BackgroundFrame) {
  lastSizeRef.value = { width: frame.width, height: frame.height };
  particlesRef.value = initParticles(frame.width, frame.height);
  basePairsRef.value = initBasePairs(frame.width, frame.height);
  initialAnimationCompleteRef.value = false;
  isShatteringRef.value = false;
  shatterProgressRef.value = 0;
  ripplesRef.value = [];
}

function draw(frame: BackgroundFrame) {
  const { ctx, width, height, mouse, time, delta } = frame;
  const mouseX = mouse.x ?? 0;
  const mouseY = mouse.y ?? 0;

  if (width !== lastSizeRef.value.width || height !== lastSizeRef.value.height) {
    lastSizeRef.value = { width, height };
    particlesRef.value = initParticles(width, height);
    basePairsRef.value = initBasePairs(width, height);
    initialAnimationCompleteRef.value = false;
    isShatteringRef.value = false;
    shatterProgressRef.value = 0;
    ripplesRef.value = [];
  }

  const quality = frame.performance.quality;
  if (quality !== 'low') {
    for (const r of frame.ripples) {
      const localRipple = ripplePoolRef.value.acquire();
      localRipple.x = r.x;
      localRipple.y = r.y;
      localRipple.radius = 0;
      localRipple.opacity = 0.8;
      ripplesRef.value.push(localRipple);
      if (!isShatteringRef.value && initialAnimationCompleteRef.value) {
        isShatteringRef.value = true;
        shatterProgressRef.value = 0;
        basePairsRef.value.forEach((basePair) => {
          const centerX = width / 2;
          const centerY = height / 2;
          const angle1 = Math.atan2(basePair.y1 - centerY, basePair.x1 - centerX);
          basePair.velocityX = Math.cos(angle1) * 10;
          basePair.velocityY = Math.sin(angle1) * 10;
          basePair.startX1 = basePair.x1;
          basePair.startY1 = basePair.y1;
          basePair.startX2 = basePair.x2;
          basePair.startY2 = basePair.y2;
          basePair.animationProgress = 0;
          basePair.trail = [];
        });
      }
    }
  }

  ctx.clearRect(0, 0, width, height);

  const t = time * 1.2;
  const waveOffset = time * 3;

  if (!initialAnimationCompleteRef.value) {
    const progress = Math.min(1, time / 2);
    basePairsRef.value.forEach((basePair) => {
      basePair.animationProgress = progress;
      basePair.trail.push({ x: basePair.x1, y: basePair.y1, opacity: 1 });
      if (basePair.trail.length > 15) {
        basePair.trail.shift();
      }
      basePair.trail.forEach((point) => {
        point.opacity *= 0.9;
      });
    });
    if (progress >= 1) {
      initialAnimationCompleteRef.value = true;
    }
  }

  if (isShatteringRef.value) {
    shatterProgressRef.value += delta;
    const shatterProgress = Math.min(1, shatterProgressRef.value / 1);
    if (shatterProgress >= 1) {
      isShatteringRef.value = false;
    }
  }

  const centerX = width / 2;
  const amplitude = 100;
  const frequency = 0.015;
  const verticalSpacing = 25;
  const helixHeight = height + 200;

  basePairsRef.value.forEach((basePair, index) => {
    const targetY = index * verticalSpacing;
    const waveAmplitude = Math.sin(waveOffset + targetY * 0.01) * 10;
    const targetX1 = centerX + Math.sin(targetY * frequency + t) * (amplitude + waveAmplitude);
    const targetX2 = centerX + Math.sin(targetY * frequency + t + Math.PI) * (amplitude + waveAmplitude);
    const z1 = Math.cos(targetY * frequency + t) * amplitude;
    const z2 = Math.cos(targetY * frequency + t + Math.PI) * amplitude;

    if (!initialAnimationCompleteRef.value) {
      const progress = basePair.animationProgress;
      const ease = 1 - Math.pow(1 - progress, 3);
      basePair.x1 = basePair.startX1 + (targetX1 - basePair.startX1) * ease;
      basePair.y1 = basePair.startY1 + (targetY - basePair.startY1) * ease;
      basePair.x2 = basePair.startX2 + (targetX2 - basePair.startX2) * ease;
      basePair.y2 = basePair.startY2 + (targetY - basePair.startY2) * ease;
    } else if (isShatteringRef.value) {
      const shatterProgress = shatterProgressRef.value / 1;
      if (shatterProgress < 0.5) {
        basePair.x1 += basePair.velocityX;
        basePair.y1 += basePair.velocityY;
        basePair.x2 += basePair.velocityX * 0.8;
        basePair.y2 += basePair.velocityY * 0.8;
        basePair.velocityX *= 0.95;
        basePair.velocityY *= 0.95;
        basePair.trail.push({ x: basePair.x1, y: basePair.y1, opacity: 1 });
        if (basePair.trail.length > 10) {
          basePair.trail.shift();
        }
        basePair.trail.forEach((point) => {
          point.opacity *= 0.8;
        });
      } else {
        const reassemblyProgress = (shatterProgress - 0.5) * 2;
        const ease = reassemblyProgress * reassemblyProgress;
        basePair.x1 = basePair.x1 + (targetX1 - basePair.x1) * ease;
        basePair.y1 = basePair.y1 + (targetY - basePair.y1) * ease;
        basePair.x2 = basePair.x2 + (targetX2 - basePair.x2) * ease;
        basePair.y2 = basePair.y2 + (targetY - basePair.y2) * ease;
        if (Math.random() < 0.3) {
          basePair.trail.push({ x: basePair.x1, y: basePair.y1, opacity: 1 });
        }
        if (basePair.trail.length > 8) {
          basePair.trail.shift();
        }
        basePair.trail.forEach((point) => {
          point.opacity *= 0.85;
        });
      }
    } else {
      basePair.x1 = targetX1;
      basePair.y1 = targetY;
      basePair.x2 = targetX2;
      basePair.y2 = targetY;
    }

    basePair.z1 = z1;
    basePair.z2 = z2;

    const dist1 = Math.sqrt(Math.pow(basePair.x1 - mouseX, 2) + Math.pow(basePair.y1 - mouseY, 2));
    const dist2 = Math.sqrt(Math.pow(basePair.x2 - mouseX, 2) + Math.pow(basePair.y2 - mouseY, 2));
    const minDist = Math.min(dist1, dist2);
    const glowRadius = 120;
    if (minDist < glowRadius) {
      basePair.glowIntensity = Math.max(0, 1 - minDist / glowRadius);
    } else {
      basePair.glowIntensity *= 0.95;
    }
    basePair.isVisible = z1 > -50 || z2 > -50;
  });

  const backboneVerticalSpacing = 8;
  const gradient1 = ctx.createLinearGradient(0, 0, 0, helixHeight);
  gradient1.addColorStop(0, 'rgba(128, 128, 128, 0.1)');
  gradient1.addColorStop(0.5, 'rgba(128, 128, 128, 0.6)');
  gradient1.addColorStop(1, 'rgba(128, 128, 128, 0.1)');
  const gradient2 = ctx.createLinearGradient(0, 0, 0, helixHeight);
  gradient2.addColorStop(0, 'rgba(169, 169, 169, 0.1)');
  gradient2.addColorStop(0.5, 'rgba(169, 169, 169, 0.6)');
  gradient2.addColorStop(1, 'rgba(169, 169, 169, 0.1)');

  ctx.beginPath();
  ctx.strokeStyle = gradient1;
  ctx.lineWidth = 4;
  ctx.lineCap = 'round';
  for (let y = -100; y < helixHeight; y += backboneVerticalSpacing) {
    const waveAmplitude = Math.sin(waveOffset + y * 0.01) * 10;
    const x1 = centerX + Math.sin(y * frequency + t) * (amplitude + waveAmplitude);
    const z1b = Math.cos(y * frequency + t) * amplitude;
    const scale1 = (z1b + amplitude) / (2 * amplitude);
    if (y === -100) {
      ctx.moveTo(x1, y);
    } else {
      ctx.globalAlpha = 0.3 + scale1 * 0.7;
      ctx.lineTo(x1, y);
    }
  }
  ctx.stroke();

  ctx.beginPath();
  ctx.strokeStyle = gradient2;
  ctx.lineWidth = 4;
  for (let y = -100; y < helixHeight; y += backboneVerticalSpacing) {
    const waveAmplitude = Math.sin(waveOffset + y * 0.01) * 10;
    const x2 = centerX + Math.sin(y * frequency + t + Math.PI) * (amplitude + waveAmplitude);
    const z2b = Math.cos(y * frequency + t + Math.PI) * amplitude;
    const scale2 = (z2b + amplitude) / (2 * amplitude);
    if (y === -100) {
      ctx.moveTo(x2, y);
    } else {
      ctx.globalAlpha = 0.3 + scale2 * 0.7;
      ctx.lineTo(x2, y);
    }
  }
  ctx.stroke();
  ctx.globalAlpha = 1;

  basePairsRef.value.forEach((basePair) => {
    if (!basePair.isVisible) return;
    const scale1 = (basePair.z1 + 100) / 200;
    const scale2 = (basePair.z2 + 100) / 200;

    if (basePair.z1 > -50) {
      ctx.globalAlpha = 0.4 + scale1 * 0.6;
      if (basePair.glowIntensity > 0) {
        ctx.shadowBlur = 20 * basePair.glowIntensity;
        ctx.shadowColor = baseColors[basePair.base1];
      }
      ctx.fillStyle = baseColors[basePair.base1];
      ctx.beginPath();
      ctx.arc(basePair.x1, basePair.y1, 8 * scale1, 0, Math.PI * 2);
      ctx.fill();
      ctx.shadowBlur = 0;
      ctx.fillStyle = 'white';
      ctx.font = `${12 * scale1}px Arial`;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(basePair.base1, basePair.x1, basePair.y1);
    }

    if (basePair.z2 > -50) {
      ctx.globalAlpha = 0.4 + scale2 * 0.6;
      if (basePair.glowIntensity > 0) {
        ctx.shadowBlur = 20 * basePair.glowIntensity;
        ctx.shadowColor = baseColors[basePair.base2];
      }
      ctx.fillStyle = baseColors[basePair.base2];
      ctx.beginPath();
      ctx.arc(basePair.x2, basePair.y2, 8 * scale2, 0, Math.PI * 2);
      ctx.fill();
      ctx.shadowBlur = 0;
      ctx.fillStyle = 'white';
      ctx.font = `${12 * scale2}px Arial`;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(basePair.base2, basePair.x2, basePair.y2);
    }
  });
  ctx.globalAlpha = 1;
  ctx.shadowBlur = 0;

  basePairsRef.value.forEach((basePair) => {
    if (!basePair.isVisible || basePair.z1 < -50 || basePair.z2 < -50) return;
    const avgZ = (basePair.z1 + basePair.z2) / 2;
    const scale = (avgZ + 100) / 200;
    const bondCount = basePair.base1 === 'A' || basePair.base1 === 'C' ? 2 : 3;
    const bondSpacing = 3;
    ctx.globalAlpha = 0.3 + scale * 0.4;
    if (basePair.glowIntensity > 0) {
      ctx.shadowBlur = 10 * basePair.glowIntensity;
      ctx.shadowColor = 'rgba(255, 255, 255, 0.8)';
      ctx.strokeStyle = `rgba(255, 255, 255, ${0.5 + basePair.glowIntensity * 0.5})`;
    } else {
      ctx.strokeStyle = connectionColor;
    }
    ctx.lineWidth = 2;
    for (let i = 0; i < bondCount; i++) {
      const offset = (i - (bondCount - 1) / 2) * bondSpacing;
      ctx.beginPath();
      ctx.moveTo(basePair.x1, basePair.y1 + offset);
      ctx.lineTo(basePair.x2, basePair.y2 + offset);
      ctx.stroke();
    }
    ctx.shadowBlur = 0;
  });
  ctx.globalAlpha = 1;

  const rng = (c: CanvasRenderingContext2D, v: { x: number; y: number }[]) => {
    c.beginPath();
    c.moveTo(v[0].x, v[0].y);
    for (let i = 1; i < v.length; i++) c.lineTo(v[i].x, v[i].y);
    c.closePath();
    c.stroke();
    c.globalAlpha *= 0.1;
    c.fill();
    c.globalAlpha /= 0.1;
  };
  const bnd = (c: CanvasRenderingContext2D, a: { x: number; y: number }, b: { x: number; y: number }) => {
    c.beginPath();
    c.moveTo(a.x, a.y);
    c.lineTo(b.x, b.y);
    c.stroke();
  };
  const dbl = (c: CanvasRenderingContext2D, a: { x: number; y: number }, b: { x: number; y: number }, g: number) => {
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const l = Math.sqrt(dx * dx + dy * dy);
    const nx = (-dy / l) * g;
    const ny = (dx / l) * g;
    c.beginPath();
    c.moveTo(a.x + nx, a.y + ny);
    c.lineTo(b.x + nx, b.y + ny);
    c.stroke();
    c.beginPath();
    c.moveTo(a.x - nx, a.y - ny);
    c.lineTo(b.x - nx, b.y - ny);
    c.stroke();
  };
  const lbl = (c: CanvasRenderingContext2D, text: string, x: number, y: number) => c.fillText(text, x, y);

  const totalH = height - 40;
  const sp = totalH / 5;
  const R = 50;
  const sr = 26;
  const mt = time;

  const structs = [
    { base: 'A', side: 'left' },
    { base: 'T', side: 'right' },
    { base: 'G', side: 'left' },
    { base: 'C', side: 'right' },
  ];

  structs.forEach((struct, idx) => {
    const base = struct.base;
    const ox = struct.side === 'left' ? 170 : width - 170;
    const offsetY = struct.side === 'left' ? 30 : -30;
    const oy = 40 + sp * (idx + 0.5) + offsetY;
    const fx =
      ox +
      Math.sin(mt * 0.7 + idx * 1.2) * 8 +
      (() => {
        const d = ox - mouseX;
        const dd = oy - mouseY;
        const dist = Math.sqrt(d * d + dd * dd);
        return dist < 250 ? (d / dist) * (250 - dist) * 0.04 : 0;
      })();
    const fy =
      oy +
      Math.cos(mt * 0.9 + idx * 1.5) * 6 +
      (() => {
        const d = ox - mouseX;
        const dd = oy - mouseY;
        const dist = Math.sqrt(d * d + dd * dd);
        return dist < 250 ? (dd / dist) * (250 - dist) * 0.04 : 0;
      })();

    ctx.save();
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    const sc = baseColors[base];

    if (base === 'A' || base === 'G') {
      ctx.strokeStyle = sc;
      ctx.fillStyle = sc;
      ctx.lineWidth = 2.2;
      ctx.globalAlpha = 0.75;
      ctx.font = 'bold 13px monospace';

      const pur = [
        { x: fx - R * 0.3, y: fy - R * 0.9, lab: 'N' },
        { x: fx + R * 0.3, y: fy - R * 0.9, lab: 'C' },
        { x: fx + R * 0.75, y: fy - R * 0.35, lab: 'N' },
        { x: fx + R * 0.6, y: fy + R * 0.15, lab: 'C' },
        { x: fx + R * 0.15, y: fy + R * 0.3, lab: 'C' },
        { x: fx - R * 0.45, y: fy + R * 0.05, lab: 'C' },
        { x: fx - R * 0.2, y: fy + R * 0.65, lab: 'N' },
        { x: fx - R * 0.55, y: fy + R * 0.45, lab: 'C' },
        { x: fx - R * 0.75, y: fy - R * 0.1, lab: 'N' },
      ];
      rng(ctx, [pur[0], pur[1], pur[2], pur[3], pur[4], pur[5]]);
      rng(ctx, [pur[3], pur[4], pur[6], pur[7], pur[8]]);

      lbl(ctx, 'N', pur[0].x - 14, pur[0].y);
      lbl(ctx, 'N', pur[2].x + 16, pur[2].y);
      lbl(ctx, 'N', pur[8].x - 14, pur[8].y);
      lbl(ctx, 'N', pur[6].x, pur[6].y + 16);
      dbl(ctx, pur[4], pur[5], 3);

      if (base === 'A') {
        lbl(ctx, 'NH₂', pur[1].x, pur[1].y - 16);
        ctx.font = 'bold 18px monospace';
        ctx.globalAlpha = 1;
        ctx.fillText('A', fx, fy + R * 1.8);
      } else {
        lbl(ctx, 'NH₂', pur[1].x, pur[1].y - 16);
        lbl(ctx, 'O', pur[5].x - 14, pur[5].y - 8);
        dbl(ctx, pur[5], { x: pur[5].x - 18, y: pur[5].y - 10 }, 2.5);
        ctx.font = 'bold 18px monospace';
        ctx.globalAlpha = 1;
        ctx.fillText('G', fx, fy + R * 1.8);
      }
    } else {
      ctx.strokeStyle = sc;
      ctx.fillStyle = sc;
      ctx.lineWidth = 2.2;
      ctx.globalAlpha = 0.75;
      ctx.font = 'bold 13px monospace';

      const pyr = [
        { x: fx - R * 0.4, y: fy - R * 0.7, lab: 'N' },
        { x: fx + R * 0.3, y: fy - R * 0.9, lab: 'C' },
        { x: fx + R * 0.75, y: fy - R * 0.25, lab: 'N' },
        { x: fx + R * 0.55, y: fy + R * 0.25, lab: 'C' },
        { x: fx + R * 0.1, y: fy + R * 0.45, lab: 'C' },
        { x: fx - R * 0.5, y: fy + R * 0.1, lab: 'C' },
      ];
      rng(ctx, pyr);
      lbl(ctx, 'N', pyr[0].x - 14, pyr[0].y);
      lbl(ctx, 'N', pyr[2].x + 16, pyr[2].y);

      if (base === 'T') {
        lbl(ctx, 'O', pyr[1].x, pyr[1].y - 22);
        dbl(ctx, pyr[1], { x: pyr[1].x, y: pyr[1].y - 16 }, 2.5);
        lbl(ctx, 'O', pyr[3].x, pyr[3].y + 22);
        dbl(ctx, pyr[3], { x: pyr[3].x, y: pyr[3].y + 16 }, 2.5);
        lbl(ctx, 'CH₃', pyr[0].x - 20, pyr[0].y - 10);
        dbl(ctx, pyr[4], pyr[5], 3);
        ctx.font = 'bold 18px monospace';
        ctx.globalAlpha = 1;
        ctx.fillText('T', fx, fy + R * 1.6);
      } else {
        lbl(ctx, 'O', pyr[1].x, pyr[1].y - 22);
        dbl(ctx, pyr[1], { x: pyr[1].x, y: pyr[1].y - 16 }, 2.5);
        lbl(ctx, 'NH₂', pyr[3].x, pyr[3].y + 22);
        dbl(ctx, pyr[4], pyr[5], 3);
        ctx.font = 'bold 18px monospace';
        ctx.globalAlpha = 1;
        ctx.fillText('C', fx, fy + R * 1.6);
      }
    }

    let baseN: { x: number; y: number };
    if (base === 'A' || base === 'G') baseN = { x: fx - R * 0.75, y: fy - R * 0.1 };
    else baseN = { x: fx - R * 0.4, y: fy - R * 0.7 };

    const sugarCY = fy + R * 1.55;
    const sugar: { x: number; y: number }[] = [];
    const sAng = [-Math.PI / 2, -Math.PI / 8, Math.PI / 3, (4 * Math.PI) / 5, (-3 * Math.PI) / 4];
    sAng.forEach((a) => sugar.push({ x: fx + sr * Math.cos(a), y: sugarCY + sr * Math.sin(a) }));

    ctx.strokeStyle = '#777';
    ctx.fillStyle = '#777';
    ctx.globalAlpha = 0.5;
    ctx.lineWidth = 1.8;
    rng(ctx, sugar);
    ctx.font = 'bold 12px monospace';
    lbl(ctx, 'O', sugar[0].x, sugar[0].y - 12);

    ctx.fillStyle = '#d44';
    ctx.globalAlpha = 0.65;
    ctx.strokeStyle = '#d44';
    ctx.lineWidth = 1.5;
    bnd(ctx, sugar[2], { x: sugar[2].x + 10, y: sugar[2].y + 14 });
    bnd(ctx, sugar[3], { x: sugar[3].x - 6, y: sugar[3].y + 20 });
    lbl(ctx, 'OH', sugar[2].x + 14, sugar[2].y + 18);
    lbl(ctx, 'OH', sugar[3].x - 10, sugar[3].y + 24);

    ctx.globalAlpha = 0.55;
    ctx.strokeStyle = '#999';
    ctx.lineWidth = 2;
    bnd(ctx, baseN, sugar[1]);

    const pAt = { x: sugar[4].x - 26, y: sugar[4].y - 16 };
    ctx.strokeStyle = '#f80';
    ctx.fillStyle = '#f80';
    ctx.globalAlpha = 0.7;
    ctx.lineWidth = 1.8;
    ctx.font = 'bold 12px monospace';
    bnd(ctx, sugar[4], pAt);
    lbl(ctx, 'P', pAt.x, pAt.y - 8);
    lbl(ctx, 'O', pAt.x - 16, pAt.y);
    lbl(ctx, 'O', pAt.x + 16, pAt.y);
    lbl(ctx, 'O⁻', pAt.x, pAt.y + 16);
    dbl(ctx, pAt, { x: pAt.x, y: pAt.y - 18 }, 2.5);

    ctx.restore();
  });

  basePairsRef.value.forEach((basePair) => {
    if (basePair.trail.length < 2) return;
    ctx.lineWidth = 2;
    ctx.lineCap = 'round';
    for (let i = 1; i < basePair.trail.length; i++) {
      const start = basePair.trail[i - 1];
      const end = basePair.trail[i];
      if (start.opacity < 0.05 || end.opacity < 0.05) continue;
      const gradient = ctx.createLinearGradient(start.x, start.y, end.x, end.y);
      gradient.addColorStop(0, `rgba(26, 136, 255, ${start.opacity * 0.5})`);
      gradient.addColorStop(1, `rgba(26, 136, 255, ${end.opacity * 0.5})`);
      ctx.strokeStyle = gradient;
      ctx.beginPath();
      ctx.moveTo(start.x, start.y);
      ctx.lineTo(end.x, end.y);
      ctx.stroke();
    }
  });

  particlesRef.value.forEach((particle) => {
    const dx = particle.x - mouseX;
    const dy = particle.y - mouseY;
    const distance = Math.sqrt(dx * dx + dy * dy);
    const repulsionRadius = 150;
    if (distance < repulsionRadius) {
      const force = (repulsionRadius - distance) / repulsionRadius;
      const angle = Math.atan2(dy, dx);
      particle.vx += Math.cos(angle) * force * 0.02;
      particle.vy += Math.sin(angle) * force * 0.02;
    }
    particle.x += particle.vx;
    particle.y += particle.vy;
    particle.angle += particle.speed;
    particle.vx += Math.cos(particle.angle) * 0.001;
    particle.vy += Math.sin(particle.angle) * 0.001;
    particle.vx *= 0.99;
    particle.vy *= 0.99;
    if (particle.x < 0) particle.x = width;
    if (particle.x > width) particle.x = 0;
    if (particle.y < 0) particle.y = height;
    if (particle.y > height) particle.y = 0;
    particle.opacity += (Math.random() - 0.5) * 0.02;
    particle.opacity = Math.max(0.1, Math.min(0.8, particle.opacity));
  });

  particlesRef.value.forEach((particle) => {
    ctx.globalAlpha = particle.opacity;
    ctx.fillStyle = sparkColor;
    ctx.beginPath();
    ctx.arc(particle.x, particle.y, particle.size, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 10;
    ctx.shadowColor = sparkColor;
    ctx.beginPath();
    ctx.arc(particle.x, particle.y, particle.size * 0.5, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;
  });
  ctx.globalAlpha = 1;

  if (quality !== 'low') {
    ripplesRef.value = ripplesRef.value.filter((ripple) => {
      ripple.radius += 5;
      ripple.opacity -= 0.02;
      if (ripple.opacity <= 0) {
        ripplePoolRef.value.release(ripple);
        return false;
      }
      return true;
    });

    for (const ripple of ripplesRef.value) {
      ctx.globalAlpha = ripple.opacity;
      ctx.strokeStyle = rippleColor;
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.arc(ripple.x, ripple.y, ripple.radius, 0, Math.PI * 2);
      ctx.stroke();
      ctx.globalAlpha = ripple.opacity * 0.5;
      ctx.beginPath();
      ctx.arc(ripple.x, ripple.y, ripple.radius * 0.5, 0, Math.PI * 2);
      ctx.stroke();
    }
  }
  ctx.globalAlpha = 1;
}
</script>
<template>
  <BackgroundCanvas
    :draw="draw"
    :init="init"
    :interactions="{ mouse: true, click: true }"
    :class-name="props.className"
  />
</template>

// src/features/shell-community/background/lib/DNASparkBackground.tsx
import { useCallback, useRef } from 'react';
import { BackgroundCanvas } from '~/features/shell-community/background/BackgroundCanvas';
import type { BackgroundFrame } from '~/features/shell-community/background/useBackgroundCanvas';
import { useColorMode } from '~/features/shell-community/background/useColorMode';
import { ObjectPool } from './objectPool';

export interface DNASparkBackgroundProps {
  sparkColor?: string;
  strandColor?: string;
  className?: string;
  particleColor?: string;
  connectionColor?: string;
  rippleColor?: string;
  color?: string;
  constfill?: string;
  text?: string;
}

interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
  size: number;
  opacity: number;
  angle: number;
  speed: number;
}

interface TrailPoint {
  x: number;
  y: number;
  opacity: number;
}

interface BasePair {
  base1: string;
  base2: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  z1: number;
  z2: number;
  glowIntensity: number;
  isVisible: boolean;
  startX1: number;
  startY1: number;
  startX2: number;
  startY2: number;
  animationProgress: number;
  velocityX: number;
  velocityY: number;
  trail: TrailPoint[];
}

interface LocalRipple {
  x: number;
  y: number;
  radius: number;
  opacity: number;
}

export default function DNASparkBackground({
  sparkColor: propSparkColor,
  strandColor: propStrandColor,
  className = '',
  particleColor: propParticleColor,
  connectionColor: propConnectionColor,
  rippleColor: propRippleColor,
  color: _color,
  constfill: _constfill,
  text: _text,
}: DNASparkBackgroundProps) {
  const mode = useColorMode();
  const sparkColor = propSparkColor || (mode === 'dark' ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.7)');
  const strandColor = propStrandColor || (mode === 'dark' ? 'rgba(64,224,208,0.6)' : 'rgba(0,0,0,0.2)');
  const particleColor = propParticleColor || (mode === 'dark' ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.7)');
  const connectionColor = propConnectionColor || (mode === 'dark' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.08)');
  const rippleColor = propRippleColor || (mode === 'dark' ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.08)');

  const ripplePoolRef = useRef(
    new ObjectPool<LocalRipple>(
      () => ({ x: 0, y: 0, radius: 0, opacity: 0 }),
      (r) => {
        r.x = 0;
        r.y = 0;
        r.radius = 0;
        r.opacity = 0;
      },
      50
    )
  );

  const particlesRef = useRef<Particle[]>([]);
  const basePairsRef = useRef<BasePair[]>([]);
  const ripplesRef = useRef<LocalRipple[]>([]);
  const initialAnimationCompleteRef = useRef(false);
  const shatterProgressRef = useRef(0);
  const isShatteringRef = useRef(false);
  const lastSizeRef = useRef<{ width: number; height: number }>({ width: 0, height: 0 });

  const baseColors: Record<string, string> = {
    A: '#1A88FF',
    T: '#E1AD37',
    G: '#AA88FF',
    C: '#AA88FF',
  };

  const getComplementaryBase = (base: string) => {
    const pairs: Record<string, string> = { A: 'T', T: 'A', G: 'C', C: 'G' };
    return pairs[base] || 'A';
  };

  const generateOrderedSequence = (length: number) => {
    const pattern = ['A', 'T', 'G', 'C'];
    return Array.from({ length }, (_, i) => pattern[i % pattern.length]);
  };

  const initParticles = (width: number, height: number) => {
    const particles: Particle[] = [];
    const numParticles = Math.floor((width * height) / 8000);
    for (let i = 0; i < numParticles; i++) {
      particles.push({
        x: Math.random() * width,
        y: Math.random() * height,
        vx: (Math.random() - 0.5) * 0.5,
        vy: (Math.random() - 0.5) * 0.5,
        size: Math.random() * 2 + 1,
        opacity: Math.random() * 0.5 + 0.3,
        angle: Math.random() * Math.PI * 2,
        speed: Math.random() * 0.02 + 0.01,
      });
    }
    return particles;
  };

  const initBasePairs = (width: number, height: number) => {
    const basePairs: BasePair[] = [];
    const sequence = generateOrderedSequence(Math.floor(height / 25));
    for (let i = 0; i < sequence.length; i++) {
      const base2 = sequence[i];
      const base1 = getComplementaryBase(base2);
      const startX1 = Math.random() * width;
      const startY1 = Math.random() * height;
      const startX2 = Math.random() * width;
      const startY2 = Math.random() * height;
      basePairs.push({
        base1,
        base2,
        x1: startX1,
        y1: startY1,
        x2: startX2,
        y2: startY2,
        z1: 0,
        z2: 0,
        glowIntensity: 0,
        isVisible: true,
        startX1,
        startY1,
        startX2,
        startY2,
        animationProgress: 0,
        velocityX: 0,
        velocityY: 0,
        trail: [],
      });
    }
    return basePairs;
  };

  const init = useCallback((_canvas: HTMLCanvasElement, frame: BackgroundFrame) => {
    lastSizeRef.current = { width: frame.width, height: frame.height };
    particlesRef.current = initParticles(frame.width, frame.height);
    basePairsRef.current = initBasePairs(frame.width, frame.height);
    initialAnimationCompleteRef.current = false;
    isShatteringRef.current = false;
    shatterProgressRef.current = 0;
    ripplesRef.current = [];
  }, []);

  const draw = useCallback(
    (frame: BackgroundFrame) => {
      const { ctx, width, height, mouse, time, delta } = frame;
      const mouseX = mouse.x ?? 0;
      const mouseY = mouse.y ?? 0;

      // 确保模式：resize 时重建
      if (width !== lastSizeRef.current.width || height !== lastSizeRef.current.height) {
        lastSizeRef.current = { width, height };
        particlesRef.current = initParticles(width, height);
        basePairsRef.current = initBasePairs(width, height);
        initialAnimationCompleteRef.current = false;
        isShatteringRef.current = false;
        shatterProgressRef.current = 0;
        ripplesRef.current = [];
      }

      // 消耗每帧涟漪批次
      const quality = frame.performance.quality;
      if (quality !== 'low') {
        for (const r of frame.ripples) {
          const localRipple = ripplePoolRef.current.acquire();
          localRipple.x = r.x;
          localRipple.y = r.y;
          localRipple.radius = 0;
          localRipple.opacity = 0.8;
          ripplesRef.current.push(localRipple);
          // 点击时触发破碎动画
          if (!isShatteringRef.current && initialAnimationCompleteRef.current) {
            isShatteringRef.current = true;
            shatterProgressRef.current = 0;
            basePairsRef.current.forEach((basePair) => {
              const centerX = width / 2;
              const centerY = height / 2;
              const angle1 = Math.atan2(basePair.y1 - centerY, basePair.x1 - centerX);
              basePair.velocityX = Math.cos(angle1) * 10;
              basePair.velocityY = Math.sin(angle1) * 10;
              basePair.startX1 = basePair.x1;
              basePair.startY1 = basePair.y1;
              basePair.startX2 = basePair.x2;
              basePair.startY2 = basePair.y2;
              basePair.animationProgress = 0;
              basePair.trail = [];
            });
          }
        }
      }

      ctx.clearRect(0, 0, width, height);

      // 将旧的每帧计数器映射到 frame.time（旧代码以约 60fps 运行）
      const t = time * 1.2;
      const waveOffset = time * 3;

      // 处理初始动画
      if (!initialAnimationCompleteRef.current) {
        const progress = Math.min(1, time / 2); // 原持续时间 2000ms
        basePairsRef.current.forEach((basePair) => {
          basePair.animationProgress = progress;
          basePair.trail.push({ x: basePair.x1, y: basePair.y1, opacity: 1 });
          if (basePair.trail.length > 15) {
            basePair.trail.shift();
          }
          basePair.trail.forEach((point) => {
            point.opacity *= 0.9;
          });
        });
        if (progress >= 1) {
          initialAnimationCompleteRef.current = true;
        }
      }

      // 处理破碎动画
      if (isShatteringRef.current) {
        shatterProgressRef.current += delta;
        const shatterProgress = Math.min(1, shatterProgressRef.current / 1); // 原持续时间 1000ms
        if (shatterProgress >= 1) {
          isShatteringRef.current = false;
        }
      }

      // DNA 双螺旋核心参数：
      // amplitude=100 螺旋半径，frequency=0.015 旋转频率，verticalSpacing=25 碱基对垂直间距
      const centerX = width / 2;
      const amplitude = 100;
      const frequency = 0.015;
      const verticalSpacing = 25;
      const helixHeight = height + 200;

      // 更新碱基对位置和发光
      basePairsRef.current.forEach((basePair, index) => {
        const targetY = index * verticalSpacing;
        const waveAmplitude = Math.sin(waveOffset + targetY * 0.01) * 10;
        const targetX1 = centerX + Math.sin(targetY * frequency + t) * (amplitude + waveAmplitude);
        const targetX2 = centerX + Math.sin(targetY * frequency + t + Math.PI) * (amplitude + waveAmplitude);
        const z1 = Math.cos(targetY * frequency + t) * amplitude;
        const z2 = Math.cos(targetY * frequency + t + Math.PI) * amplitude;

        if (!initialAnimationCompleteRef.current) {
          const progress = basePair.animationProgress;
          const ease = 1 - Math.pow(1 - progress, 3);
          basePair.x1 = basePair.startX1 + (targetX1 - basePair.startX1) * ease;
          basePair.y1 = basePair.startY1 + (targetY - basePair.startY1) * ease;
          basePair.x2 = basePair.startX2 + (targetX2 - basePair.startX2) * ease;
          basePair.y2 = basePair.startY2 + (targetY - basePair.startY2) * ease;
        } else if (isShatteringRef.current) {
          const shatterProgress = shatterProgressRef.current / 1;
          if (shatterProgress < 0.5) {
            basePair.x1 += basePair.velocityX;
            basePair.y1 += basePair.velocityY;
            basePair.x2 += basePair.velocityX * 0.8;
            basePair.y2 += basePair.velocityY * 0.8;
            basePair.velocityX *= 0.95;
            basePair.velocityY *= 0.95;
            basePair.trail.push({ x: basePair.x1, y: basePair.y1, opacity: 1 });
            if (basePair.trail.length > 10) {
              basePair.trail.shift();
            }
            basePair.trail.forEach((point) => {
              point.opacity *= 0.8;
            });
          } else {
            const reassemblyProgress = (shatterProgress - 0.5) * 2;
            const ease = reassemblyProgress * reassemblyProgress;
            basePair.x1 = basePair.x1 + (targetX1 - basePair.x1) * ease;
            basePair.y1 = basePair.y1 + (targetY - basePair.y1) * ease;
            basePair.x2 = basePair.x2 + (targetX2 - basePair.x2) * ease;
            basePair.y2 = basePair.y2 + (targetY - basePair.y2) * ease;
            if (Math.random() < 0.3) {
              basePair.trail.push({ x: basePair.x1, y: basePair.y1, opacity: 1 });
            }
            if (basePair.trail.length > 8) {
              basePair.trail.shift();
            }
            basePair.trail.forEach((point) => {
              point.opacity *= 0.85;
            });
          }
        } else {
          basePair.x1 = targetX1;
          basePair.y1 = targetY;
          basePair.x2 = targetX2;
          basePair.y2 = targetY;
        }

        basePair.z1 = z1;
        basePair.z2 = z2;

        const dist1 = Math.sqrt(Math.pow(basePair.x1 - mouseX, 2) + Math.pow(basePair.y1 - mouseY, 2));
        const dist2 = Math.sqrt(Math.pow(basePair.x2 - mouseX, 2) + Math.pow(basePair.y2 - mouseY, 2));
        const minDist = Math.min(dist1, dist2);
        const glowRadius = 120;
        if (minDist < glowRadius) {
          basePair.glowIntensity = Math.max(0, 1 - minDist / glowRadius);
        } else {
          basePair.glowIntensity *= 0.95;
        }
        basePair.isVisible = z1 > -50 || z2 > -50;
      });

      // 绘制骨架
      const backboneVerticalSpacing = 8;
      const gradient1 = ctx.createLinearGradient(0, 0, 0, helixHeight);
      gradient1.addColorStop(0, 'rgba(128, 128, 128, 0.1)');
      gradient1.addColorStop(0.5, 'rgba(128, 128, 128, 0.6)');
      gradient1.addColorStop(1, 'rgba(128, 128, 128, 0.1)');
      const gradient2 = ctx.createLinearGradient(0, 0, 0, helixHeight);
      gradient2.addColorStop(0, 'rgba(169, 169, 169, 0.1)');
      gradient2.addColorStop(0.5, 'rgba(169, 169, 169, 0.6)');
      gradient2.addColorStop(1, 'rgba(169, 169, 169, 0.1)');

      ctx.beginPath();
      ctx.strokeStyle = gradient1;
      ctx.lineWidth = 4;
      ctx.lineCap = 'round';
      for (let y = -100; y < helixHeight; y += backboneVerticalSpacing) {
        const waveAmplitude = Math.sin(waveOffset + y * 0.01) * 10;
        const x1 = centerX + Math.sin(y * frequency + t) * (amplitude + waveAmplitude);
        const z1 = Math.cos(y * frequency + t) * amplitude;
        const scale1 = (z1 + amplitude) / (2 * amplitude);
        if (y === -100) {
          ctx.moveTo(x1, y);
        } else {
          ctx.globalAlpha = 0.3 + scale1 * 0.7;
          ctx.lineTo(x1, y);
        }
      }
      ctx.stroke();

      ctx.beginPath();
      ctx.strokeStyle = gradient2;
      ctx.lineWidth = 4;
      for (let y = -100; y < helixHeight; y += backboneVerticalSpacing) {
        const waveAmplitude = Math.sin(waveOffset + y * 0.01) * 10;
        const x2 = centerX + Math.sin(y * frequency + t + Math.PI) * (amplitude + waveAmplitude);
        const z2 = Math.cos(y * frequency + t + Math.PI) * amplitude;
        const scale2 = (z2 + amplitude) / (2 * amplitude);
        if (y === -100) {
          ctx.moveTo(x2, y);
        } else {
          ctx.globalAlpha = 0.3 + scale2 * 0.7;
          ctx.lineTo(x2, y);
        }
      }
      ctx.stroke();
      ctx.globalAlpha = 1;

      // 绘制碱基对
      basePairsRef.current.forEach((basePair) => {
        if (!basePair.isVisible) return;
        const scale1 = (basePair.z1 + 100) / 200;
        const scale2 = (basePair.z2 + 100) / 200;

        if (basePair.z1 > -50) {
          ctx.globalAlpha = 0.4 + scale1 * 0.6;
          if (basePair.glowIntensity > 0) {
            ctx.shadowBlur = 20 * basePair.glowIntensity;
            ctx.shadowColor = baseColors[basePair.base1];
          }
          ctx.fillStyle = baseColors[basePair.base1];
          ctx.beginPath();
          ctx.arc(basePair.x1, basePair.y1, 8 * scale1, 0, Math.PI * 2);
          ctx.fill();
          ctx.shadowBlur = 0;
          ctx.fillStyle = 'white';
          ctx.font = `${12 * scale1}px Arial`;
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillText(basePair.base1, basePair.x1, basePair.y1);
        }

        if (basePair.z2 > -50) {
          ctx.globalAlpha = 0.4 + scale2 * 0.6;
          if (basePair.glowIntensity > 0) {
            ctx.shadowBlur = 20 * basePair.glowIntensity;
            ctx.shadowColor = baseColors[basePair.base2];
          }
          ctx.fillStyle = baseColors[basePair.base2];
          ctx.beginPath();
          ctx.arc(basePair.x2, basePair.y2, 8 * scale2, 0, Math.PI * 2);
          ctx.fill();
          ctx.shadowBlur = 0;
          ctx.fillStyle = 'white';
          ctx.font = `${12 * scale2}px Arial`;
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillText(basePair.base2, basePair.x2, basePair.y2);
        }
      });
      ctx.globalAlpha = 1;
      ctx.shadowBlur = 0;

      // 绘制碱基对连接线
      basePairsRef.current.forEach((basePair) => {
        if (!basePair.isVisible || basePair.z1 < -50 || basePair.z2 < -50) return;
        const avgZ = (basePair.z1 + basePair.z2) / 2;
        const scale = (avgZ + 100) / 200;
        const bondCount = basePair.base1 === 'A' || basePair.base1 === 'C' ? 2 : 3;
        const bondSpacing = 3;
        ctx.globalAlpha = 0.3 + scale * 0.4;
        if (basePair.glowIntensity > 0) {
          ctx.shadowBlur = 10 * basePair.glowIntensity;
          ctx.shadowColor = 'rgba(255, 255, 255, 0.8)';
          ctx.strokeStyle = `rgba(255, 255, 255, ${0.5 + basePair.glowIntensity * 0.5})`;
        } else {
          ctx.strokeStyle = connectionColor;
        }
        ctx.lineWidth = 2;
        for (let i = 0; i < bondCount; i++) {
          const offset = (i - (bondCount - 1) / 2) * bondSpacing;
          ctx.beginPath();
          ctx.moveTo(basePair.x1, basePair.y1 + offset);
          ctx.lineTo(basePair.x2, basePair.y2 + offset);
          ctx.stroke();
        }
        ctx.shadowBlur = 0;
      });
      ctx.globalAlpha = 1;

      // 绘制分子结构
      const rng = (c: CanvasRenderingContext2D, v: { x: number; y: number }[]) => {
        c.beginPath();
        c.moveTo(v[0].x, v[0].y);
        for (let i = 1; i < v.length; i++) c.lineTo(v[i].x, v[i].y);
        c.closePath();
        c.stroke();
        c.globalAlpha *= 0.1;
        c.fill();
        c.globalAlpha /= 0.1;
      };
      const bnd = (c: CanvasRenderingContext2D, a: { x: number; y: number }, b: { x: number; y: number }) => {
        c.beginPath();
        c.moveTo(a.x, a.y);
        c.lineTo(b.x, b.y);
        c.stroke();
      };
      const dbl = (
        c: CanvasRenderingContext2D,
        a: { x: number; y: number },
        b: { x: number; y: number },
        g: number
      ) => {
        const dx = b.x - a.x;
        const dy = b.y - a.y;
        const l = Math.sqrt(dx * dx + dy * dy);
        const nx = (-dy / l) * g;
        const ny = (dx / l) * g;
        c.beginPath();
        c.moveTo(a.x + nx, a.y + ny);
        c.lineTo(b.x + nx, b.y + ny);
        c.stroke();
        c.beginPath();
        c.moveTo(a.x - nx, a.y - ny);
        c.lineTo(b.x - nx, b.y - ny);
        c.stroke();
      };
      const lbl = (c: CanvasRenderingContext2D, text: string, x: number, y: number) => c.fillText(text, x, y);

      const totalH = height - 40;
      const sp = totalH / 5;
      const R = 50;
      const sr = 26;
      const mt = time; // 替代 Date.now() * 0.001

      const structs = [
        { base: 'A', side: 'left' },
        { base: 'T', side: 'right' },
        { base: 'G', side: 'left' },
        { base: 'C', side: 'right' },
      ];

      structs.forEach((struct, idx) => {
        const base = struct.base;
        const ox = struct.side === 'left' ? 170 : width - 170;
        const offsetY = struct.side === 'left' ? 30 : -30;
        const oy = 40 + sp * (idx + 0.5) + offsetY;
        const fx =
          ox +
          Math.sin(mt * 0.7 + idx * 1.2) * 8 +
          (() => {
            const d = ox - mouseX;
            const dd = oy - mouseY;
            const dist = Math.sqrt(d * d + dd * dd);
            return dist < 250 ? (d / dist) * (250 - dist) * 0.04 : 0;
          })();
        const fy =
          oy +
          Math.cos(mt * 0.9 + idx * 1.5) * 6 +
          (() => {
            const d = ox - mouseX;
            const dd = oy - mouseY;
            const dist = Math.sqrt(d * d + dd * dd);
            return dist < 250 ? (dd / dist) * (250 - dist) * 0.04 : 0;
          })();

        ctx.save();
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        const sc = baseColors[base];

        if (base === 'A' || base === 'G') {
          ctx.strokeStyle = sc;
          ctx.fillStyle = sc;
          ctx.lineWidth = 2.2;
          ctx.globalAlpha = 0.75;
          ctx.font = 'bold 13px monospace';

          const pur = [
            { x: fx - R * 0.3, y: fy - R * 0.9, lab: 'N' },
            { x: fx + R * 0.3, y: fy - R * 0.9, lab: 'C' },
            { x: fx + R * 0.75, y: fy - R * 0.35, lab: 'N' },
            { x: fx + R * 0.6, y: fy + R * 0.15, lab: 'C' },
            { x: fx + R * 0.15, y: fy + R * 0.3, lab: 'C' },
            { x: fx - R * 0.45, y: fy + R * 0.05, lab: 'C' },
            { x: fx - R * 0.2, y: fy + R * 0.65, lab: 'N' },
            { x: fx - R * 0.55, y: fy + R * 0.45, lab: 'C' },
            { x: fx - R * 0.75, y: fy - R * 0.1, lab: 'N' },
          ];
          rng(ctx, [pur[0], pur[1], pur[2], pur[3], pur[4], pur[5]]);
          rng(ctx, [pur[3], pur[4], pur[6], pur[7], pur[8]]);

          lbl(ctx, 'N', pur[0].x - 14, pur[0].y);
          lbl(ctx, 'N', pur[2].x + 16, pur[2].y);
          lbl(ctx, 'N', pur[8].x - 14, pur[8].y);
          lbl(ctx, 'N', pur[6].x, pur[6].y + 16);
          dbl(ctx, pur[4], pur[5], 3);

          if (base === 'A') {
            lbl(ctx, 'NH₂', pur[1].x, pur[1].y - 16);
            ctx.font = 'bold 18px monospace';
            ctx.globalAlpha = 1;
            ctx.fillText('A', fx, fy + R * 1.8);
          } else {
            lbl(ctx, 'NH₂', pur[1].x, pur[1].y - 16);
            lbl(ctx, 'O', pur[5].x - 14, pur[5].y - 8);
            dbl(ctx, pur[5], { x: pur[5].x - 18, y: pur[5].y - 10 }, 2.5);
            ctx.font = 'bold 18px monospace';
            ctx.globalAlpha = 1;
            ctx.fillText('G', fx, fy + R * 1.8);
          }
        } else {
          ctx.strokeStyle = sc;
          ctx.fillStyle = sc;
          ctx.lineWidth = 2.2;
          ctx.globalAlpha = 0.75;
          ctx.font = 'bold 13px monospace';

          const pyr = [
            { x: fx - R * 0.4, y: fy - R * 0.7, lab: 'N' },
            { x: fx + R * 0.3, y: fy - R * 0.9, lab: 'C' },
            { x: fx + R * 0.75, y: fy - R * 0.25, lab: 'N' },
            { x: fx + R * 0.55, y: fy + R * 0.25, lab: 'C' },
            { x: fx + R * 0.1, y: fy + R * 0.45, lab: 'C' },
            { x: fx - R * 0.5, y: fy + R * 0.1, lab: 'C' },
          ];
          rng(ctx, pyr);
          lbl(ctx, 'N', pyr[0].x - 14, pyr[0].y);
          lbl(ctx, 'N', pyr[2].x + 16, pyr[2].y);

          if (base === 'T') {
            lbl(ctx, 'O', pyr[1].x, pyr[1].y - 22);
            dbl(ctx, pyr[1], { x: pyr[1].x, y: pyr[1].y - 16 }, 2.5);
            lbl(ctx, 'O', pyr[3].x, pyr[3].y + 22);
            dbl(ctx, pyr[3], { x: pyr[3].x, y: pyr[3].y + 16 }, 2.5);
            lbl(ctx, 'CH₃', pyr[0].x - 20, pyr[0].y - 10);
            dbl(ctx, pyr[4], pyr[5], 3);
            ctx.font = 'bold 18px monospace';
            ctx.globalAlpha = 1;
            ctx.fillText('T', fx, fy + R * 1.6);
          } else {
            lbl(ctx, 'O', pyr[1].x, pyr[1].y - 22);
            dbl(ctx, pyr[1], { x: pyr[1].x, y: pyr[1].y - 16 }, 2.5);
            lbl(ctx, 'NH₂', pyr[3].x, pyr[3].y + 22);
            dbl(ctx, pyr[4], pyr[5], 3);
            ctx.font = 'bold 18px monospace';
            ctx.globalAlpha = 1;
            ctx.fillText('C', fx, fy + R * 1.6);
          }
        }

        let baseN: { x: number; y: number };
        if (base === 'A' || base === 'G') baseN = { x: fx - R * 0.75, y: fy - R * 0.1 };
        else baseN = { x: fx - R * 0.4, y: fy - R * 0.7 };

        const sugarCY = fy + R * 1.55;
        const sugar: { x: number; y: number }[] = [];
        const sAng = [-Math.PI / 2, -Math.PI / 8, Math.PI / 3, (4 * Math.PI) / 5, (-3 * Math.PI) / 4];
        sAng.forEach((a) => sugar.push({ x: fx + sr * Math.cos(a), y: sugarCY + sr * Math.sin(a) }));

        ctx.strokeStyle = '#777';
        ctx.fillStyle = '#777';
        ctx.globalAlpha = 0.5;
        ctx.lineWidth = 1.8;
        rng(ctx, sugar);
        ctx.font = 'bold 12px monospace';
        lbl(ctx, 'O', sugar[0].x, sugar[0].y - 12);

        ctx.fillStyle = '#d44';
        ctx.globalAlpha = 0.65;
        ctx.strokeStyle = '#d44';
        ctx.lineWidth = 1.5;
        bnd(ctx, sugar[2], { x: sugar[2].x + 10, y: sugar[2].y + 14 });
        bnd(ctx, sugar[3], { x: sugar[3].x - 6, y: sugar[3].y + 20 });
        lbl(ctx, 'OH', sugar[2].x + 14, sugar[2].y + 18);
        lbl(ctx, 'OH', sugar[3].x - 10, sugar[3].y + 24);

        ctx.globalAlpha = 0.55;
        ctx.strokeStyle = '#999';
        ctx.lineWidth = 2;
        bnd(ctx, baseN, sugar[1]);

        const pAt = { x: sugar[4].x - 26, y: sugar[4].y - 16 };
        ctx.strokeStyle = '#f80';
        ctx.fillStyle = '#f80';
        ctx.globalAlpha = 0.7;
        ctx.lineWidth = 1.8;
        ctx.font = 'bold 12px monospace';
        bnd(ctx, sugar[4], pAt);
        lbl(ctx, 'P', pAt.x, pAt.y - 8);
        lbl(ctx, 'O', pAt.x - 16, pAt.y);
        lbl(ctx, 'O', pAt.x + 16, pAt.y);
        lbl(ctx, 'O⁻', pAt.x, pAt.y + 16);
        dbl(ctx, pAt, { x: pAt.x, y: pAt.y - 18 }, 2.5);

        ctx.restore();
      });

      // 绘制动画轨迹
      basePairsRef.current.forEach((basePair) => {
        if (basePair.trail.length < 2) return;
        ctx.lineWidth = 2;
        ctx.lineCap = 'round';
        for (let i = 1; i < basePair.trail.length; i++) {
          const start = basePair.trail[i - 1];
          const end = basePair.trail[i];
          if (start.opacity < 0.05 || end.opacity < 0.05) continue;
          const gradient = ctx.createLinearGradient(start.x, start.y, end.x, end.y);
          gradient.addColorStop(0, `rgba(26, 136, 255, ${start.opacity * 0.5})`);
          gradient.addColorStop(1, `rgba(26, 136, 255, ${end.opacity * 0.5})`);
          ctx.strokeStyle = gradient;
          ctx.beginPath();
          ctx.moveTo(start.x, start.y);
          ctx.lineTo(end.x, end.y);
          ctx.stroke();
        }
      });

      // 更新粒子
      particlesRef.current.forEach((particle) => {
        const dx = particle.x - mouseX;
        const dy = particle.y - mouseY;
        const distance = Math.sqrt(dx * dx + dy * dy);
        const repulsionRadius = 150;
        if (distance < repulsionRadius) {
          const force = (repulsionRadius - distance) / repulsionRadius;
          const angle = Math.atan2(dy, dx);
          particle.vx += Math.cos(angle) * force * 0.02;
          particle.vy += Math.sin(angle) * force * 0.02;
        }
        particle.x += particle.vx;
        particle.y += particle.vy;
        particle.angle += particle.speed;
        particle.vx += Math.cos(particle.angle) * 0.001;
        particle.vy += Math.sin(particle.angle) * 0.001;
        particle.vx *= 0.99;
        particle.vy *= 0.99;
        if (particle.x < 0) particle.x = width;
        if (particle.x > width) particle.x = 0;
        if (particle.y < 0) particle.y = height;
        if (particle.y > height) particle.y = 0;
        particle.opacity += (Math.random() - 0.5) * 0.02;
        particle.opacity = Math.max(0.1, Math.min(0.8, particle.opacity));
      });

      // 绘制粒子
      particlesRef.current.forEach((particle) => {
        ctx.globalAlpha = particle.opacity;
        ctx.fillStyle = sparkColor;
        ctx.beginPath();
        ctx.arc(particle.x, particle.y, particle.size, 0, Math.PI * 2);
        ctx.fill();
        ctx.shadowBlur = 10;
        ctx.shadowColor = sparkColor;
        ctx.beginPath();
        ctx.arc(particle.x, particle.y, particle.size * 0.5, 0, Math.PI * 2);
        ctx.fill();
        ctx.shadowBlur = 0;
      });
      ctx.globalAlpha = 1;

      // 更新点击涟漪
      if (quality !== 'low') {
        ripplesRef.current = ripplesRef.current.filter((ripple) => {
          ripple.radius += 5;
          ripple.opacity -= 0.02;
          if (ripple.opacity <= 0) {
            ripplePoolRef.current.release(ripple);
            return false;
          }
          return true;
        });

        // 绘制点击涟漪
        for (const ripple of ripplesRef.current) {
          ctx.globalAlpha = ripple.opacity;
          ctx.strokeStyle = rippleColor;
          ctx.lineWidth = 3;
          ctx.beginPath();
          ctx.arc(ripple.x, ripple.y, ripple.radius, 0, Math.PI * 2);
          ctx.stroke();
          ctx.globalAlpha = ripple.opacity * 0.5;
          ctx.beginPath();
          ctx.arc(ripple.x, ripple.y, ripple.radius * 0.5, 0, Math.PI * 2);
          ctx.stroke();
        }
      }
      ctx.globalAlpha = 1;
    },
    [sparkColor, strandColor, particleColor, connectionColor, rippleColor]
  );

  return <BackgroundCanvas draw={draw} init={init} interactions={{ mouse: true, click: true }} className={className} />;
}
