// src/features/starhope/components-vue/AuthGuard.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useAuthStore } from '../stores-vue/auth';
import StarHopeLoginRequired from '../routes-vue/StarHopeLoginRequired.vue';

const { isLoggedIn } = useAuthStore();
</script>

<template>
  <StarHopeLoginRequired v-if="!isLoggedIn" />
  <slot v-else />
</template>

// src/features/starhope/hooks/AuthGuard.svelte
<script lang="ts">
  import { authStore } from '~/features/starhope/stores/auth.svelte';
  import StarHopeLoginRequired from '~/features/starhope/routes/StarHopeLoginRequired.svelte';

  let { children } = $props<{ children: import('svelte').Snippet }>();

  const isLoggedIn = $derived(authStore.isLoggedIn);
</script>

{#if !isLoggedIn}
  <StarHopeLoginRequired />
{:else}
  {@render children()}
{/if}
