// src/features/shell/components/widget/DisplaySettings.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import I18nKey from '~/core/i18n/i18nKey';
import { i18n } from '~/core/i18n/translation';
import { Icon } from '@iconify/vue';
import { getDefaultHue, getHue, setHue } from '~/core/utils/setting-utils';

const hue = ref(typeof window !== 'undefined' ? getHue() : 250);
const defaultHue = typeof window !== 'undefined' ? getDefaultHue() : 250;

function resetHue() {
  hue.value = getDefaultHue();
}

watch(hue, (val) => {
  if (val !== undefined) {
    setHue(val);
  }
});
</script>

<template>
  <div
    id="display-setting"
    class="float-panel float-panel-closed absolute transition-all w-80 right-4 px-4 py-4"
  >
    <div class="flex flex-row gap-2 mb-3 items-center justify-between">
      <div
        class="flex gap-2 font-bold text-lg text-neutral-900 dark:text-neutral-100 transition relative ml-3
          before:w-1 before:h-4 before:rounded-md before:bg-[var(--primary)]
          before:absolute before:-left-3 before:top-[0.33rem]"
      >
        {{ i18n(I18nKey.themeColor) }}
        <button
          aria-label="Reset to Default"
          class="btn-regular w-7 h-7 rounded-md active:scale-90 will-change-transform"
          :class="{ 'opacity-0 pointer-events-none': hue === defaultHue }"
          @click="resetHue"
        >
          <div class="text-[var(--btn-content)]">
            <Icon icon="fa6-solid:arrow-rotate-left" class="text-[0.875rem]" />
          </div>
        </button>
      </div>
      <div class="flex gap-1">
        <div
          id="hueValue"
          class="transition bg-[var(--btn-regular-bg)] w-10 h-7 rounded-md flex justify-center
            font-bold text-sm items-center text-[var(--btn-content)]"
        >
          {{ hue }}
        </div>
      </div>
    </div>
    <div class="w-full h-6 px-1 bg-[oklch(0.80_0.10_0)] dark:bg-[oklch(0.70_0.10_0)] rounded select-none">
      <input
        :aria-label="i18n(I18nKey.themeColor)"
        type="range"
        min="0"
        max="360"
        v-model.number="hue"
        class="slider"
        id="colorSlider"
        step="5"
        style="width: 100%"
      />
    </div>
  </div>
</template>

<style scoped>
#display-setting input[type='range'] {
  -webkit-appearance: none;
  height: 1.5rem;
  background-image: var(--color-selection-bar);
  transition: background-image 0.15s ease-in-out;
}
#display-setting input[type='range']::-webkit-slider-thumb {
  -webkit-appearance: none;
  height: 1rem;
  width: 0.5rem;
  border-radius: 0.125rem;
  background: rgba(255, 255, 255, 0.7);
  box-shadow: none;
}
#display-setting input[type='range']::-webkit-slider-thumb:hover {
  background: rgba(255, 255, 255, 0.8);
}
#display-setting input[type='range']::-webkit-slider-thumb:active {
  background: rgba(255, 255, 255, 0.6);
}
#display-setting input[type='range']::-moz-range-thumb {
  height: 1rem;
  width: 0.5rem;
  border-radius: 0.125rem;
  border-width: 0;
  background: rgba(255, 255, 255, 0.7);
  box-shadow: none;
}
#display-setting input[type='range']::-moz-range-thumb:hover {
  background: rgba(255, 255, 255, 0.8);
}
#display-setting input[type='range']::-moz-range-thumb:active {
  background: rgba(255, 255, 255, 0.6);
}
</style>

// src/features/shell/components/widget/DisplaySettings.svelte
<script lang="ts">
import I18nKey from '~/core/i18n/i18nKey';
import { i18n } from '~/core/i18n/translation';
import Icon from "@iconify/svelte";
import { getDefaultHue, getHue, setHue } from '~/core/utils/setting-utils';

let hue = $state(getHue());
const defaultHue = getDefaultHue();

function resetHue() {
	hue = getDefaultHue();
}

$effect(() => {
	if (hue !== undefined) {
		setHue(hue);
	}
});
</script>

<div id="display-setting" class="float-panel float-panel-closed absolute transition-all w-80 right-4 px-4 py-4">
    <div class="flex flex-row gap-2 mb-3 items-center justify-between">
        <div class="flex gap-2 font-bold text-lg text-neutral-900 dark:text-neutral-100 transition relative ml-3
            before:w-1 before:h-4 before:rounded-md before:bg-[var(--primary)]
            before:absolute before:-left-3 before:top-[0.33rem]"
        >
            {i18n(I18nKey.themeColor)}
            <button aria-label="Reset to Default" class="btn-regular w-7 h-7 rounded-md  active:scale-90 will-change-transform"
                    class:opacity-0={hue === defaultHue} class:pointer-events-none={hue === defaultHue} onclick={resetHue}>
                <div class="text-[var(--btn-content)]">
                    <Icon icon="fa6-solid:arrow-rotate-left" class="text-[0.875rem]"></Icon>
                </div>
            </button>
        </div>
        <div class="flex gap-1">
            <div id="hueValue" class="transition bg-[var(--btn-regular-bg)] w-10 h-7 rounded-md flex justify-center
            font-bold text-sm items-center text-[var(--btn-content)]">
                {hue}
            </div>
        </div>
    </div>
    <div class="w-full h-6 px-1 bg-[oklch(0.80_0.10_0)] dark:bg-[oklch(0.70_0.10_0)] rounded select-none">
        <input aria-label={i18n(I18nKey.themeColor)} type="range" min="0" max="360" bind:value={hue}
               class="slider" id="colorSlider" step="5" style="width: 100%">
    </div>
</div>


<style>
    #display-setting input[type="range"] {
        -webkit-appearance: none;
        height: 1.5rem;
        background-image: var(--color-selection-bar);
        transition: background-image 0.15s ease-in-out;
    }
    #display-setting input[type="range"]::-webkit-slider-thumb {
        -webkit-appearance: none;
        height: 1rem;
        width: 0.5rem;
        border-radius: 0.125rem;
        background: rgba(255, 255, 255, 0.7);
        box-shadow: none;
    }
    #display-setting input[type="range"]::-webkit-slider-thumb:hover {
        background: rgba(255, 255, 255, 0.8);
    }
    #display-setting input[type="range"]::-webkit-slider-thumb:active {
        background: rgba(255, 255, 255, 0.6);
    }
    #display-setting input[type="range"]::-moz-range-thumb {
        height: 1rem;
        width: 0.5rem;
        border-radius: 0.125rem;
        border-width: 0;
        background: rgba(255, 255, 255, 0.7);
        box-shadow: none;
    }
    #display-setting input[type="range"]::-moz-range-thumb:hover {
        background: rgba(255, 255, 255, 0.8);
    }
    #display-setting input[type="range"]::-moz-range-thumb:active {
        background: rgba(255, 255, 255, 0.6);
    }
    #display-setting input[type="range"]::-ms-thumb {
        height: 1rem;
        width: 0.5rem;
        border-radius: 0.125rem;
        background: rgba(255, 255, 255, 0.7);
        box-shadow: none;
    }
    #display-setting input[type="range"]::-ms-thumb:hover {
        background: rgba(255, 255, 255, 0.8);
    }
    #display-setting input[type="range"]::-ms-thumb:active {
        background: rgba(255, 255, 255, 0.6);
    }
</style>
