// src/components/auth/ProtectedRoute.tsx
import type { ReactNode } from 'react';
import { useAuth } from './AuthProvider';

interface Props {
  children: ReactNode;
  fallback?: ReactNode;
}

export function ProtectedRoute({ children, fallback }: Props) {
  const { state } = useAuth();

  if (!state.isLoggedIn) {
    return (
      fallback || (
        <div className="flex flex-col items-center justify-center min-h-[50vh] gap-4">
          <div className="text-6xl">🔒</div>
          <p className="text-lg text-base-content">请先登录后再访问此页面</p>
          <a href="/login" className="btn btn-primary">前往登录</a>
        </div>
      )
    );
  }

  return <>{children}</>;
}

// src/features/auth/components/settings/ProtectedRoute.vue
<template>
  <div v-if="!auth.state.isLoggedIn" class="flex items-center justify-center min-h-[40vh]">
    <div class="text-center">
      <h2 class="text-xl font-semibold text-deep-text mb-2">请先登录</h2>
      <p class="text-text-muted mb-4">访问此页面需要登录</p>
      <a href="/login" class="btn btn-primary">前往登录</a>
    </div>
  </div>
  <slot v-else />
</template>

<script setup lang="ts">
import { useAuth } from '../../composables/useAuth';

const auth = useAuth();
</script>
