// src/components/background/BackgroundCanvas.tsx
import type { ReactNode } from 'react';
import { useBackgroundCanvas, type BackgroundInteractions, type BackgroundFrame } from './useBackgroundCanvas';

export interface BackgroundCanvasProps {
  draw: (frame: BackgroundFrame) => void;
  init?: (canvas: HTMLCanvasElement, frame: BackgroundFrame) => void | (() => void);
  interactions?: BackgroundInteractions;
  className?: string;
  /** 如 DreamyHalo 的 blurOverlay 覆盖层 */
  children?: ReactNode;
}

export function BackgroundCanvas({ draw, init, interactions, className = '', children }: BackgroundCanvasProps) {
  const { canvasRef } = useBackgroundCanvas({ draw, init, interactions });
  return (
    <>
      <canvas
        ref={canvasRef}
        className={`fixed inset-0 pointer-events-auto ${className}`}
        style={{ zIndex: 0, width: '100vw', height: '100vh' }}
        aria-hidden="true"
      />
      {children}
    </>

  );
}

// src/features/shell/background/vue/BackgroundCanvas.vue
<script setup lang="ts">
import { useBackgroundCanvas, type BackgroundInteractions, type BackgroundFrame } from './useBackgroundCanvas';

const props = defineProps<{
  draw: (frame: BackgroundFrame) => void;
  init?: (canvas: HTMLCanvasElement, frame: BackgroundFrame) => void | (() => void);
  interactions?: BackgroundInteractions;
  className?: string;
}>();

const { canvasRef } = useBackgroundCanvas({ draw: props.draw, init: props.init, interactions: props.interactions });
</script>

<template>
  <canvas
    ref="canvasRef"
    :class="`fixed inset-0 pointer-events-auto ${props.className ?? ''}`"
    style="z-index: 0; width: 100vw; height: 100vh"
    aria-hidden="true"
  />
  <slot />
</template>
