// src/features/starhope/components/StarHopeRouter.svelte
<script lang="ts">
  import AuthGuard from '~/features/starhope/hooks/AuthGuard.svelte';
  import StarHopeLoginRequired from '~/features/starhope/routes/StarHopeLoginRequired.svelte';
  import StarHopeDashboard from '~/features/starhope/routes/StarHopeDashboard.svelte';
  import StarHopeBank from '~/features/starhope/routes/StarHopeBank.svelte';
  import StarHopePractice from '~/features/starhope/routes/StarHopePractice.svelte';
  import StarHopeExam from '~/features/starhope/routes/StarHopeExam.svelte';
  import StarHopeWrongBook from '~/features/starhope/routes/StarHopeWrongBook.svelte';
  import StarHopeAi from '~/features/starhope/routes/StarHopeAi.svelte';
  import StarHopeReader from '~/features/starhope/routes/StarHopeReader.svelte';
  import StarHopePlugins from '~/features/starhope/routes/StarHopePlugins.svelte';
  import StarHopeSettings from '~/features/starhope/routes/StarHopeSettings.svelte';
  import { navigation, type StarHopeRoute } from '~/features/starhope/stores/navigation.svelte';

  const { currentRoute: current } = navigation;

  const routeTable: Record<StarHopeRoute, unknown> = {
    login: StarHopeLoginRequired,
    dashboard: StarHopeDashboard,
    bank: StarHopeBank,
    practice: StarHopePractice,
    exam: StarHopeExam,
    'wrong-book': StarHopeWrongBook,
    ai: StarHopeAi,
    reader: StarHopeReader,
    plugins: StarHopePlugins,
    settings: StarHopeSettings,
  };
</script>

{#if current === 'login'}
  <StarHopeLoginRequired />
{:else}
  <AuthGuard>
    {#each Object.keys(routeTable) as key}
      {#if current === key}
        {#if key === 'dashboard'}
          <StarHopeDashboard />
        {:else if key === 'bank'}
          <StarHopeBank />
        {:else if key === 'practice'}
          <StarHopePractice />
        {:else if key === 'exam'}
          <StarHopeExam />
        {:else if key === 'wrong-book'}
          <StarHopeWrongBook />
        {:else if key === 'ai'}
          <StarHopeAi />
        {:else if key === 'reader'}
          <StarHopeReader />
        {:else if key === 'plugins'}
          <StarHopePlugins />
        {:else if key === 'settings'}
          <StarHopeSettings />
        {:else}
          <StarHopeDashboard />
        {/if}
      {/if}
    {/each}
  </AuthGuard>
{/if}

// src/features/starhope/components-vue/StarHopeRouter.vue
<script setup lang="ts">
import { defineAsyncComponent } from 'vue';
import AuthGuard from './AuthGuard.vue';
import StarHopeLoginRequired from '../routes-vue/StarHopeLoginRequired.vue';
import { useNavigationStore } from '../stores-vue/navigation';

const { currentRoute } = useNavigationStore();

const routes: Record<string, any> = {
  dashboard: defineAsyncComponent(() => import('../routes-vue/StarHopeDashboard.vue')),
  bank: defineAsyncComponent(() => import('../routes-vue/StarHopeBank.vue')),
  practice: defineAsyncComponent(() => import('../routes-vue/StarHopePractice.vue')),
  exam: defineAsyncComponent(() => import('../routes-vue/StarHopeExam.vue')),
  'wrong-book': defineAsyncComponent(() => import('../routes-vue/StarHopeWrongBook.vue')),
  ai: defineAsyncComponent(() => import('../routes-vue/StarHopeAi.vue')),
  reader: defineAsyncComponent(() => import('../routes-vue/StarHopeReader.vue')),
  plugins: defineAsyncComponent(() => import('../routes-vue/StarHopePlugins.vue')),
  settings: defineAsyncComponent(() => import('../routes-vue/StarHopeSettings.vue')),
};
</script>

<template>
  <StarHopeLoginRequired v-if="currentRoute === 'login'" />
  <AuthGuard v-else>
    <component :is="routes[currentRoute] || routes.dashboard" />
  </AuthGuard>
</template>
