// src/features/starhope/components/StarHopeShell.svelte
<script lang="ts">
  import StarHopeLayout from '~/features/starhope/components/StarHopeLayout.svelte';
  import StarHopeRouter from '~/features/starhope/components/StarHopeRouter.svelte';
</script>

<div class="starhope-app min-h-screen bg-page-bg text-default">
  <StarHopeLayout>
    <StarHopeRouter />
  </StarHopeLayout>
</div>

// src/features/starhope/components-vue/StarHopeShell.vue
<script setup lang="ts">
import StarHopeLayout from './StarHopeLayout.vue';
import StarHopeRouter from './StarHopeRouter.vue';
</script>

<template>
  <div class="starhope-app min-h-screen bg-page-bg text-default">
    <StarHopeLayout>
      <StarHopeRouter />
    </StarHopeLayout>
  </div>
</template>
